---
title: "practicing safe paths"
output: github_document
---

```{r}
library(here)
#here::here(data_foo, "species.csv")
#here:here()
```

```{r}
fs::path_home()
```

## Example Code from 00_filesystem-practice_jenny.R

## Copy again, using fs ----
library(fs)
(from_dir <- path_home("Desktop", "day1_s1_explore-libraries"))
(from_files <- dir_ls(from_dir, glob = "*.R"))
(to_files <- path_file(from_files))
(out <- file_copy(from_files, to_files))
dir_ls()
dir_info()


```{}
library(fs)
#path_home("Desktop", "day1_s1_explore-libraries")
#path_home("Desktop")
(from_dir <- path_home("..", "Desktop",
                       "day1_s1_explore-libraries"))
dir_ls()
(from_files <- dir_ls(from_dir, glob = "*.R"))
(to_files <- path_file(from_files))
(out <- file_copy(from_files, to_files))
dir_ls()
dir_info()
```

```{r}
# \\.R$
library(fs)
(from_dir <- path_home("..", "Desktop",
                       "day1_s1_explore-libraries"))
dir_ls(from_dir, glob = "*.R")
```


### Session Info

```{r}
devtools::session_info()
```

